# This is a basic workflow to help you get started with Actions

name: Call-reuasable-workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    name: Call the latest version on main branch
    uses: petrmo/actionstests/.github/workflows/reusable-workflow.yml@main
    with: 
      input1: "Main-branch1"
      input2: "Main-branch2"
   
  reusableworkflow:
    name: Call the latest version on reusableworkflow branch
    uses: petrmo/actionstests/.github/workflows/reusable-workflow.yml@reusableworkflow
    with: 
      input1: "reusableworkflow1"
      input2: "reusableworkflow2"
      
  local:
    name: Call the latest version on local branch
    uses: ./.github/workflows/reusable-workflow.yml
    with: 
      input1: "local1"
      input2: "local2"
  
    

    
