name: Passing Variables between jobs on self hosted and github runners

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run: 
    shell: cmd
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  A:
    # The type of runner that the job will run on - windows no quots on set-output!, how to make $GITHUB_ENV working???
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set var 1 with set-output
        id: Var1Step
        run: |
          echo ::set-output name=Var1::ThisisVar1
          echo "%Var1% -- ${{env.Var1}} -- ${{steps.Var1Step.outputs.Var1}}"
      - name: Show var 1
        run: echo "%Var1% -- ${{env.Var1}} -- ${{steps.Var1Step.outputs.Var1}}"
      
    outputs:
      Var1Out: ${{steps.Var1Step.outputs.Var1}}

           
  B:
      # The type of runner that the job will run on
      runs-on: windows-latest
      needs: [A]

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Show job A output
          run: echo ${{needs.A.outputs.Var1Out}} 
  C:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      needs: [A]
      defaults:
        run: 
          shell: bash

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Show job A output
          run: echo ${{needs.A.outputs.Var1Out}} 
        - name: Set var 2 with set-output
          id: Var2Step
          run: |
            echo ::set-output name=Var2::ThisisVar2
            echo "%Var2% -- ${{env.Var2}} -- ${{steps.Var2Step.outputs.Var2}}"
        - name: Show var 1
          run: echo "%Var2% -- ${{env.Var2}} -- ${{steps.Var1Step.outputs.Var2}}"

      outputs:
        Var2Out: ${{steps.Var2Step.outputs.Var2}}  
        
  D:
      # The type of runner that the job will run on
      runs-on: self-hosted
      needs: [C]

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Show job C output
          run: echo ${{needs.C.outputs.Var2Out}} 
