# This is a basic workflow to help you get started with Actions

name: Report Actions Usage

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: ActionsDesk/report-action-usage@v2.1.2
        id: action-uses
        with:
          token: ${{ secrets.REPORT_ACTIONS_PAT }}
          owner: petrmo
          csv: reports/actions-used.csv
          md: reports/actions-used.md
          push_results_to_repo: true

      # example: output
      - run: |
          echo "${{ steps.action-uses.outputs.csv_result }}"
          echo "${{ steps.action-uses.outputs.md_result }}"
