name: TempTest

on:

  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: windows-latest

    
    steps:
      - name: set var1
        id: buildnumber3
        run: |
          echo "::set-output name=build_number::1.0.1"
      - name: set var2
        id: Release_Name
        shell: powershell
        env:
          ReleaseName: 'MnS.TMS.MQAdapter.Articles.QueueReader-${{ steps.buildnumber3.outputs.build_number }}'
        run: |
          echo "${{env.ReleaseName}}"
          echo "::set-output name=BUILDR_NAME:: ${{env.ReleaseName}} "
          echo "::set-output name=BUILDR_NAME2::${{env.ReleaseName}} "
          echo "::set-output name=BUILDR_NAME3::${{env.ReleaseName}}"
        

      - name: Print ReleaseName
        run: |
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME }}"  
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME2 }}"  
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME3 }}"  

