name: TempTest

on:

  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: windows-latest

    
    steps:
      - name: set var
        id: Release_Name
        run: |
          echo "::set-output name=BUILDR_NAME:: XXX "
          echo "::set-output name=BUILDR_NAME2::XXX "
          echo "::set-output name=BUILDR_NAME3::XXX"
        

      - name: Print ReleaseName
        run: |
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME }}"  
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME2 }}"  
          echo "${{ steps.Release_Name.outputs.BUILDR_NAME3 }}"  

