# This is a basic workflow to help you get started with Actions

name: Workflow Trigger

# Controls when the workflow will run
on:
  workflow_run:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Show the event
        run: |
          echo "The event ${{ github.event.workflow_run }}"
          
