# This is a basic workflow to help you get started with Actions

name: Workflow Trigger

# Controls when the workflow will run
on:
  workflow_run:
    workflows: 
      - PassingVariables
    types: 
      - requested
      - completed
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
    
      # Runs a set of commands using the runners shell
      # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-50
      - name: Show the event
        run: |
          echo "The workflow run id: ${{ github.event.workflow_run.workflow_id }}"
          echo "The workflow run name: ${{ github.event.workflow_run.name }}"
          echo "The workflow run url: ${{ github.event.workflow_run.workflow_url }}"
          echo "The workflow run event: ${{ github.event.workflow_run.event }}"
          echo "The workflow run status: ${{ github.event.workflow_run.status }}"
          echo "The workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "The workflow id: ${{ github.event.workflow.id }}"
          echo "The workflow name: ${{ github.event.workflow.name }}"
          echo "The workflow url: ${{ github.event.workflow.url }}"
          echo "The sender type: ${{ github.event.sender.type }}"
          echo "The sender login: ${{ github.event.sender.login }}"
          
          
